For issue 77 - DRY issue in template_sampling module
arfc/annsa pull request #78
Opened 2019-09-08 18:39 UTC by kamuda1

Adds new function in template_sampling to remove duplicate code. Tests for new function and other template_sampling functions are included.

2019-09-08 18:39 UTC, pep8speaks commented
Hello @kamuda1! Thanks for opening this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:

* In the file [`annsa/template_sampling.py`](https://github.com/arfc/annsa/blob/4503aabba974b4971f5ea2f45dd6bac769d090d6/annsa/template_sampling.py):

> [Line 139:1](https://github.com/arfc/annsa/blob/4503aabba974b4971f5ea2f45dd6bac769d090d6/annsa/template_sampling.py#L139): [W293](https://duckduckgo.com/?q=pep8%20W293) blank line contains whitespace
> [Line 222:26](https://github.com/arfc/annsa/blob/4503aabba974b4971f5ea2f45dd6bac769d090d6/annsa/template_sampling.py#L222): [E225](https://duckduckgo.com/?q=pep8%20E225) missing whitespace around operator

* In the file [`annsa/tests/test_templatesampling.py`](https://github.com/arfc/annsa/blob/4503aabba974b4971f5ea2f45dd6bac769d090d6/annsa/tests/test_templatesampling.py):

> [Line 1:53](https://github.com/arfc/annsa/blob/4503aabba974b4971f5ea2f45dd6bac769d090d6/annsa/tests/test_templatesampling.py#L1): [W291](https://duckduckgo.com/?q=pep8%20W291) trailing whitespace

2019-09-09 16:33 UTC, katyhuff requested changes

2019-09-09 16:33 UTC, katyhuff commented on annsa/template_sampling.py
> +    This function manipulates a spectral template.
can you be more specific?

2019-09-09 16:33 UTC, katyhuff commented on annsa/tests/test_templatesampling.py
> +# define lamba = 1000
this should go in a setup fixture.

2019-09-09 16:35 UTC, katyhuff commented
Flake 8 : 

```bash
/home/circleci/annsa/annsa/template_sampling.py:215:13: E123 closing bracket does not match indentation of opening bracket's line
/home/circleci/annsa/annsa/template_sampling.py:228:13: E123 closing bracket does not match indentation of opening bracket's line
/home/circleci/annsa/annsa/template_sampling.py:240:13: E126 continuation line over-indented for hanging indent
/home/circleci/annsa/annsa/template_sampling.py:244:13: E123 closing bracket does not match indentation of opening bracket's line
```

2019-09-12 19:14 UTC, samgdotson approved these changes
I think these changes make sense. The tests are good.

2019-09-16 14:49 UTC, kamuda1 reviewed
All changes have been made.

2019-09-16 14:50 UTC, kamuda1 commented
@katyhuff The changes have been made, I think this is good to merge.

2019-09-16 15:32 UTC, katyhuff approved these changes

2019-09-16 15:32 UTC, merged