adds sequential keras models
arfc/annsa pull request #84
Opened 2019-12-01 19:54 UTC by kamuda1

Adds all notebooks used for the dissertation.

2019-12-01 19:54 UTC, pep8speaks commented
Hello @kamuda1! Thanks for opening this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:

* In the file [`annsa/model_classes_sequential.py`](https://github.com/arfc/annsa/blob/dde5ebab8381139388581196411bbbffa46752ff/annsa/model_classes_sequential.py):

> [Line 9:80](https://github.com/arfc/annsa/blob/dde5ebab8381139388581196411bbbffa46752ff/annsa/model_classes_sequential.py#L9): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (114 > 79 characters)
> [Line 15:1](https://github.com/arfc/annsa/blob/dde5ebab8381139388581196411bbbffa46752ff/annsa/model_classes_sequential.py#L15): [E302](https://duckduckgo.com/?q=pep8%20E302) expected 2 blank lines, found 1
> [Line 17:59](https://github.com/arfc/annsa/blob/dde5ebab8381139388581196411bbbffa46752ff/annsa/model_classes_sequential.py#L17): [W291](https://duckduckgo.com/?q=pep8%20W291) trailing whitespace
> [Line 64:80](https://github.com/arfc/annsa/blob/dde5ebab8381139388581196411bbbffa46752ff/annsa/model_classes_sequential.py#L64): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (84 > 79 characters)
> [Line 79:80](https://github.com/arfc/annsa/blob/dde5ebab8381139388581196411bbbffa46752ff/annsa/model_classes_sequential.py#L79): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (87 > 79 characters)
> [Line 85:80](https://github.com/arfc/annsa/blob/dde5ebab8381139388581196411bbbffa46752ff/annsa/model_classes_sequential.py#L85): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (83 > 79 characters)
> [Line 94:61](https://github.com/arfc/annsa/blob/dde5ebab8381139388581196411bbbffa46752ff/annsa/model_classes_sequential.py#L94): [W291](https://duckduckgo.com/?q=pep8%20W291) trailing whitespace
> [Line 107:80](https://github.com/arfc/annsa/blob/dde5ebab8381139388581196411bbbffa46752ff/annsa/model_classes_sequential.py#L107): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (84 > 79 characters)
> [Line 126:80](https://github.com/arfc/annsa/blob/dde5ebab8381139388581196411bbbffa46752ff/annsa/model_classes_sequential.py#L126): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (80 > 79 characters)
> [Line 180:80](https://github.com/arfc/annsa/blob/dde5ebab8381139388581196411bbbffa46752ff/annsa/model_classes_sequential.py#L180): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (80 > 79 characters)
> [Line 182:48](https://github.com/arfc/annsa/blob/dde5ebab8381139388581196411bbbffa46752ff/annsa/model_classes_sequential.py#L182): [W291](https://duckduckgo.com/?q=pep8%20W291) trailing whitespace
> [Line 186:80](https://github.com/arfc/annsa/blob/dde5ebab8381139388581196411bbbffa46752ff/annsa/model_classes_sequential.py#L186): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (85 > 79 characters)
> [Line 190:80](https://github.com/arfc/annsa/blob/dde5ebab8381139388581196411bbbffa46752ff/annsa/model_classes_sequential.py#L190): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (81 > 79 characters)
> [Line 193:80](https://github.com/arfc/annsa/blob/dde5ebab8381139388581196411bbbffa46752ff/annsa/model_classes_sequential.py#L193): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (83 > 79 characters)
> [Line 193:84](https://github.com/arfc/annsa/blob/dde5ebab8381139388581196411bbbffa46752ff/annsa/model_classes_sequential.py#L193): [W291](https://duckduckgo.com/?q=pep8%20W291) trailing whitespace
> [Line 196:1](https://github.com/arfc/annsa/blob/dde5ebab8381139388581196411bbbffa46752ff/annsa/model_classes_sequential.py#L196): [W293](https://duckduckgo.com/?q=pep8%20W293) blank line contains whitespace
> [Line 211:1](https://github.com/arfc/annsa/blob/dde5ebab8381139388581196411bbbffa46752ff/annsa/model_classes_sequential.py#L211): [W293](https://duckduckgo.com/?q=pep8%20W293) blank line contains whitespace
> [Line 223:1](https://github.com/arfc/annsa/blob/dde5ebab8381139388581196411bbbffa46752ff/annsa/model_classes_sequential.py#L223): [W293](https://duckduckgo.com/?q=pep8%20W293) blank line contains whitespace
> [Line 226:1](https://github.com/arfc/annsa/blob/dde5ebab8381139388581196411bbbffa46752ff/annsa/model_classes_sequential.py#L226): [W293](https://duckduckgo.com/?q=pep8%20W293) blank line contains whitespace
> [Line 241:1](https://github.com/arfc/annsa/blob/dde5ebab8381139388581196411bbbffa46752ff/annsa/model_classes_sequential.py#L241): [W293](https://duckduckgo.com/?q=pep8%20W293) blank line contains whitespace
> [Line 244:1](https://github.com/arfc/annsa/blob/dde5ebab8381139388581196411bbbffa46752ff/annsa/model_classes_sequential.py#L244): [W293](https://duckduckgo.com/?q=pep8%20W293) blank line contains whitespace
> [Line 269:1](https://github.com/arfc/annsa/blob/dde5ebab8381139388581196411bbbffa46752ff/annsa/model_classes_sequential.py#L269): [E302](https://duckduckgo.com/?q=pep8%20E302) expected 2 blank lines, found 1
> [Line 275:5](https://github.com/arfc/annsa/blob/dde5ebab8381139388581196411bbbffa46752ff/annsa/model_classes_sequential.py#L275): [E125](https://duckduckgo.com/?q=pep8%20E125) continuation line with same indent as next logical line
> [Line 294:61](https://github.com/arfc/annsa/blob/dde5ebab8381139388581196411bbbffa46752ff/annsa/model_classes_sequential.py#L294): [W291](https://duckduckgo.com/?q=pep8%20W291) trailing whitespace
> [Line 307:80](https://github.com/arfc/annsa/blob/dde5ebab8381139388581196411bbbffa46752ff/annsa/model_classes_sequential.py#L307): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (84 > 79 characters)
> [Line 320:1](https://github.com/arfc/annsa/blob/dde5ebab8381139388581196411bbbffa46752ff/annsa/model_classes_sequential.py#L320): [W293](https://duckduckgo.com/?q=pep8%20W293) blank line contains whitespace
> [Line 325:9](https://github.com/arfc/annsa/blob/dde5ebab8381139388581196411bbbffa46752ff/annsa/model_classes_sequential.py#L325): [E125](https://duckduckgo.com/?q=pep8%20E125) continuation line with same indent as next logical line
> [Line 337:45](https://github.com/arfc/annsa/blob/dde5ebab8381139388581196411bbbffa46752ff/annsa/model_classes_sequential.py#L337): [W291](https://duckduckgo.com/?q=pep8%20W291) trailing whitespace
> [Line 340:29](https://github.com/arfc/annsa/blob/dde5ebab8381139388581196411bbbffa46752ff/annsa/model_classes_sequential.py#L340): [W291](https://duckduckgo.com/?q=pep8%20W291) trailing whitespace
> [Line 343:80](https://github.com/arfc/annsa/blob/dde5ebab8381139388581196411bbbffa46752ff/annsa/model_classes_sequential.py#L343): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (80 > 79 characters)
> [Line 429:80](https://github.com/arfc/annsa/blob/dde5ebab8381139388581196411bbbffa46752ff/annsa/model_classes_sequential.py#L429): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (85 > 79 characters)
> [Line 433:80](https://github.com/arfc/annsa/blob/dde5ebab8381139388581196411bbbffa46752ff/annsa/model_classes_sequential.py#L433): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (81 > 79 characters)
> [Line 436:80](https://github.com/arfc/annsa/blob/dde5ebab8381139388581196411bbbffa46752ff/annsa/model_classes_sequential.py#L436): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (83 > 79 characters)
> [Line 460:1](https://github.com/arfc/annsa/blob/dde5ebab8381139388581196411bbbffa46752ff/annsa/model_classes_sequential.py#L460): [W293](https://duckduckgo.com/?q=pep8%20W293) blank line contains whitespace
> [Line 472:1](https://github.com/arfc/annsa/blob/dde5ebab8381139388581196411bbbffa46752ff/annsa/model_classes_sequential.py#L472): [W293](https://duckduckgo.com/?q=pep8%20W293) blank line contains whitespace
> [Line 477:20](https://github.com/arfc/annsa/blob/dde5ebab8381139388581196411bbbffa46752ff/annsa/model_classes_sequential.py#L477): [E251](https://duckduckgo.com/?q=pep8%20E251) unexpected spaces around keyword / parameter equals
> [Line 477:22](https://github.com/arfc/annsa/blob/dde5ebab8381139388581196411bbbffa46752ff/a [...]

2019-12-04 17:52 UTC, samgdotson commented
Updating branch, waiting for circle ci

2020-12-30 17:04 UTC, samgdotson requested changes
CircleCI failed with this code
```bash
Using SSH Config Dir /home/circleci/.ssh
Cloning into '.'...
Warning: Permanently added the RSA host key for IP address '140.82.112.3' to the list of known hosts.
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

exit status 128
```
It doesn't appear to be a test error, but there's something wrong here. RIP to this year old PR. Sorry @kamuda1

2025-03-18 19:45 UTC, katyhuff commented
Merging for posterity even though circle ci is having issues. Tests should be runnable locally.

2025-03-18 19:45 UTC, merged